# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1A1313)
$foreground = rgb(DAF5FD)
$color0 = rgb(423A3B)
$color1 = rgb(108FB8)
$color2 = rgb(B56EA7)
$color3 = rgb(B87E66)
$color4 = rgb(B68369)
$color5 = rgb(B8864F)
$color6 = rgb(70AABC)
$color7 = rgb(C2E8F4)
$color8 = rgb(88A3AB)
$color9 = rgb(15BFF5)
$color10 = rgb(F292DF)
$color11 = rgb(F5A888)
$color12 = rgb(F3AF8C)
$color13 = rgb(F6B269)
$color14 = rgb(96E2FA)
$color15 = rgb(C2E8F4)
